# Copyright (c) 2025 DebVisor contributors
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#     http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Placeholder NGINX ingress controller manifest (simplified)
# This file is NOT a complete ingress deployment. It only
# sketches a namespace and a minimal controller Deployment.
# For any real deployment, use the official ingress-nginx
# Helm chart/manifests and follow their documentation. Do
# NOT use this placeholder in production clusters.
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
  # debvisor.io/addon and debvisor.io/tenant are optional labels you can
  # use to group addons and tenants for observability and policy.
  # debvisor.io/addon: "ingress-nginx"
  # debvisor.io/tenant: "default"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress-nginx-controller
  namespace: ingress-nginx
  # debvisor.io/addon: "ingress-nginx"
  # debvisor.io/tenant: "default"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingress-nginx
  template:
    metadata:
      labels:
        app: ingress-nginx
        # debvisor.io/addon: "ingress-nginx"
        # debvisor.io/tenant: "default"
    spec:
      containers:
      - name: controller
        image: quay.io/kubernetes-ingress-controller/nginx-ingress-controller:latest
        args:
        - /nginx-ingress-controller
        - --publish-service=ingress-nginx/ingress-nginx-controller
        ports:
        - containerPort: 80
        - containerPort: 443
