name: Common Reusable

on:
  workflow_call:
    inputs:
      install-yamllint:
        required: false
        type: boolean
        default: true
      install-kubectl:
        required: false
        type: boolean
        default: false
      kubectl-version:
        required: false
        type: string
        default: "v1.30.0"

defaults:
  run:
    shell: bash

jobs:
  setup:
    runs-on: self-hosted
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Python
        if: inputs.install-yamllint == true
        uses: actions/setup-python@v6
        with:
          python-version: '3.10'

      - name: Install yamllint
        if: inputs.install-yamllint == true
        run: pip install yamllint

      - name: Install kubectl
        if: inputs.install-kubectl == true
        uses: azure/setup-kubectl@v4
        with:
          version: "${{ inputs.kubectl-version }}"
