name: Markdown Lint

on:
  pull_request:
    paths:
      - '**/*.md'
      - '.markdownlint.jsonc'
  push:
    branches: [ main, master ]
    paths:
      - '**/*.md'
      - '.markdownlint.jsonc'

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    concurrency:
      group: markdownlint-${{ github.ref }}
      cancel-in-progress: true
    permissions:
      contents: read
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Run markdownlint-cli2
        uses: DavidAnson/markdownlint-cli2-action@b4c9feab76d8025d1e83c653fa3990936df0e6c8 # v16
        with:
          globs: |
            **/*.md
      - name: Upload markdownlint report
        if: failure()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: markdownlint-logs
          path: '**/*.md'
