name: Markdown Lint

on:
  pull_request:
    paths:
      - '**/*.md'
      - '.markdownlint.jsonc'
  push:
    branches: [ main, master ]
    paths:
      - '**/*.md'
      - '.markdownlint.jsonc'

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    concurrency:
      group: markdownlint-${{ github.ref }}
      cancel-in-progress: true
    permissions:
      contents: read
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run markdownlint-cli2
        uses: DavidAnson/markdownlint-cli2-action@v16
        with:
          globs: |
            **/*.md
      - name: Upload markdownlint report
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: markdownlint-logs
          path: '**/*.md'
