name: Validate Fixtures (redirect)
on:
  push:
    paths:
    - monitoring/fixtures/**
  pull_request:
    paths:
    - monitoring/fixtures/**
  workflow_dispatch: null
defaults:
  run:
    shell: bash
jobs:
  call-combined:
    uses: ./.github/workflows/validate-configs.yml
    with:
      paths: monitoring/fixtures/**
    secrets: inherit
'on':
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
